/**
 * Source for the inline `subagent-artifact` CLI helper.
 *
 * The launch script generated by interactive-tmux.ts writes this script body
 * to `$ARTIFACT_DIR/cli.mjs` (via a heredoc) and invokes it for lifecycle,
 * WIP, and output events. The wrapper shell and the child pi process both
 * inherit $ARTIFACT_DIR and call the helper.
 *
 * Keeping the source as a single string means there's no build step, no
 * extra file in the published package, and no path-resolution concerns when
 * the extension is loaded from arbitrary cwd's.
 *
 * Subcommands:
 *   start                       — write a `started` event
 *   wip "<message>" [--progress N/M]
 *                               — write a `wip` event
 *   output                      — read stdin and atomically replace output.md
 *   done <exitCode>             — write a `done` event with the child's exit code
 *   error "<message>"           — write an `error` event
 *   cancelled                   — write a `cancelled` event
 *
 * Exit codes: 0 on success, 2 on usage error (missing env var / unknown cmd).
 */

/**
 * The body of the CLI as a string, written verbatim to
 * `$ARTIFACT_DIR/cli.mjs` by `writeLaunchScript`. The string is the literal
 * JavaScript the child process executes.
 */
export const CLI_SOURCE = String.raw`#!/usr/bin/env node
// Generated by pi-subagentura. Writes lifecycle/WIP/output events to the
// artifact directory (\$ARTIFACT_DIR). Subcommands: start, wip, output,
// done, error, cancelled. See subagent-artifact-cli.ts for the source.
import { appendFileSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const dir = process.env.ARTIFACT_DIR;
if (!dir) {
  process.stderr.write("ARTIFACT_DIR not set\n");
  process.exit(2);
}
mkdirSync(dir, { recursive: true, mode: 0o700 });

const statusFile = join(dir, "events.ndjson");
const outputFile = join(dir, "output.md");

const cmd = process.argv[2];
const arg = process.argv[3];
const ts = Date.now();
const write = (obj) => appendFileSync(statusFile, JSON.stringify(obj) + "\n", { mode: 0o600 });

switch (cmd) {
  case "start":
    write({ ts, type: "started", status: "running" });
    break;
  case "wip": {
    const message = arg ?? "";
    const progressFlag = process.argv[4];
    let progress;
    if (progressFlag === "--progress" && process.argv[5]) {
      const [cs, ts2] = process.argv[5].split("/");
      const current = Number(cs);
      const total = ts2 !== undefined ? Number(ts2) : undefined;
      if (Number.isFinite(current)) {
        progress = { current, ...(Number.isFinite(total) ? { total } : {}) };
      }
    }
    write({ ts, type: "wip", status: "wip", message, ...(progress ? { progress } : {}) });
    break;
  }
  case "output": {
    const chunks = [];
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (c) => chunks.push(c));
    process.stdin.on("end", () => {
      const content = chunks.join("");
      const tmp = outputFile + ".tmp";
      writeFileSync(tmp, content, { mode: 0o600 });
      renameSync(tmp, outputFile);
      appendFileSync(
        join(dirname(outputFile), "events.ndjson"),
        JSON.stringify({ ts: Date.now(), type: "output_updated", status: "running" }) + "\n",
        { mode: 0o600 },
      );
    });
    break;
  }
  case "done": {
    const exitCode = Number(arg ?? 0);
    const status = exitCode === 0 ? "done" : "error";
    write({ ts, type: "done", status, exitCode });
    break;
  }
  case "error":
    write({ ts, type: "error", status: "error", message: arg ?? "unknown error" });
    break;
  case "cancelled":
    write({ ts, type: "cancelled", status: "cancelled" });
    break;
  default:
    process.stderr.write("Unknown command: " + cmd + "\n");
    process.exit(2);
}
`;

/** Test-only helper: write the CLI to a file and chmod it. */
export function writeCliScript(targetPath: string): void {
	const { writeFileSync, chmodSync } = require("node:fs") as typeof import("node:fs");
	writeFileSync(targetPath, CLI_SOURCE, { mode: 0o700 });
	chmodSync(targetPath, 0o700);
}
