/**
 * Source for the inline `subagent-artifact` CLI helper.
 *
 * The launch script generated by interactive-tmux.ts writes this script body
 * to `$ARTIFACT_DIR/cli.mjs` (via a heredoc) and invokes it for lifecycle
 * events. The wrapper shell writes `started` / `done` / `cancelled`; the
 * child pi process writes `done` / `error` itself.
 *
 * Keeping the source as a single string means there's no build step, no
 * extra file in the published package, and no path-resolution concerns when
 * the extension is loaded from arbitrary cwd's.
 *
 * Subcommands:
 *   start                       — write a `started` event
 *   done <exitCode>             — write a `done` event with the child's exit code
 *   error "<message>"           — write an `error` event
 *   cancelled                   — write a `cancelled` event
 *
 * Exit codes: 0 on success, 2 on usage error (missing env var / unknown cmd).
 */


/**
 * The body of the CLI as a string, written verbatim to
 * `$ARTIFACT_DIR/cli.mjs` by `writeLaunchScript`. The string is the literal
 * JavaScript the child process executes.
 */
export const CLI_SOURCE = String.raw`#!/usr/bin/env node
// Generated by pi-subagentura. Writes lifecycle events to the artifact
// directory (\$ARTIFACT_DIR). Subcommands: start, done, error, cancelled.
// See subagent-artifact-cli.ts for the source.
import { appendFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const dir = process.env.ARTIFACT_DIR;
if (!dir) {
  process.stderr.write("ARTIFACT_DIR not set\n");
  process.exit(2);
}
mkdirSync(dir, { recursive: true, mode: 0o700 });

const statusFile = join(dir, "events.ndjson");

const cmd = process.argv[2];
const arg = process.argv[3];
const ts = Date.now();
const write = (obj) => appendFileSync(statusFile, JSON.stringify(obj) + "\n", { mode: 0o600 });

switch (cmd) {
  case "start":
    write({ ts, type: "started", status: "running" });
    break;
  case "done": {
    const exitCode = Number(arg ?? 0);
    const status = exitCode === 0 ? "done" : "error";
    write({ ts, type: "done", status, exitCode });
    break;
  }
  case "error":
    write({ ts, type: "error", status: "error", message: arg ?? "unknown error" });
    break;
  case "cancelled":
    write({ ts, type: "cancelled", status: "cancelled" });
    break;
  default:
    process.stderr.write("Unknown command: " + cmd + "\n");
    process.exit(2);
}
`;



/** Test-only helper: write the CLI to a file and chmod it. */
export function writeCliScript(targetPath: string): void {
	const { writeFileSync, chmodSync } = require("node:fs") as typeof import("node:fs");
	writeFileSync(targetPath, CLI_SOURCE, { mode: 0o700 });
	chmodSync(targetPath, 0o700);
}
